version: "3.8"

services:
  backend:
    container_name: backend
    environment:
      spring.datasource.url: jdbc:mysql://mysql:3306/ntsboard
      spring.datasource.username: root
      spring.datasource.password: 1234
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

  mysql:
    image: mysql:8.0.34
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ntsboard
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
